package com.swordHostDemo.controller;

import com.alibaba.fastjson.JSONObject;

import java.util.HashMap;

/**
 * @date: 2023/2/8 20:37
 * @description: window 专题，识别杀软程序
 */
public class antivirusConntroller {


    //原始json文件
    public static String antivirusConntroller() {
        String json = "{\n" +
                "\t\"360tray.exe\": \"360安全卫士-实时保护\",\n" +
                "\t\"360safe.exe\": \"360安全卫士-主程序\",\n" +
                "\t\"ZhuDongFangYu.exe\": \"360安全卫士-主动防御\",\n" +
                "\t\"360skylarsvc\": \"360终端安全管理系统\",\n" +
                "\t\"360sd.exe\": \"360杀毒\",\n" +
                "\t\"a2guard.exe\": \"a-squared杀毒\",\n" +
                "\t\"ad-watch.exe\": \"Lavasoft杀毒\",\n" +
                "\t\"cleaner8.exe\": \"The Cleaner杀毒\",\n" +
                "\t\"vba32lder.exe\": \"vb32杀毒\",\n" +
                "\t\"MongoosaGUI.exe\": \"Mongoosa杀毒\",\n" +
                "\t\"CorantiControlCenter32.exe\": \"Coranti2012杀毒\",\n" +
                "\t\"F-PROT.exe\": \"F-Prot AntiVirus\",\n" +
                "\t\"CMCTrayIcon.exe\": \"CMC杀毒\",\n" +
                "\t\"K7TSecurity.exe\": \"K7杀毒\",\n" +
                "\t\"UnThreat.exe\": \"UnThreat杀毒\",\n" +
                "\t\"CKSoftShiedAntivirus4.exe\": \"Shield Antivirus杀毒\",\n" +
                "\t\"AVWatchService.exe\": \"VIRUSfighter杀毒\",\n" +
                "\t\"ArcaTasksService.exe\": \"ArcaVir杀毒\",\n" +
                "\t\"iptray.exe\": \"Immunet杀毒\",\n" +
                "\t\"PSafeSysTray.exe\": \"PSafe杀毒\",\n" +
                "\t\"nspupsvc.exe\": \"nProtect杀毒\",\n" +
                "\t\"SpywareTerminatorShield.exe\": \"SpywareTerminator杀毒\",\n" +
                "\t\"BKavService.exe\": \"Bkav杀毒\",\n" +
                "\t\"MsMpEng.exe\": \"Microsoft Security Essentials\",\n" +
                "\t\"NisSrv.exe\": \"Microsoft Security Essentials\",\n" +
                "\t\"MsSense.exe\": \"Microsoft Security Essentials\",\n" +
                "\t\"msseces.exe\": \"Microsoft Security Essentials\",\n" +
                "\t\"MpCmdRun.exe\": \"Windows Defender Antivirus\",\n" +
                "\t\"SBAMSvc.exe\": \"VIPRE\",\n" +
                "\t\"ccSvcHst.exe\": \"Norton杀毒\",\n" +
                "\t\"f-secure.exe\": \"冰岛\",\n" +
                "\t\"avp.exe\": \"Kaspersky\",\n" +
                "\t\"KvMonXP.exe\": \"江民杀毒\",\n" +
                "\t\"RavMonD.exe\": \"瑞星杀毒\",\n" +
                "\t\"Mcshield.exe\": \"Mcafee\",\n" +
                "\t\"Tbmon.exe\": \"Mcafee\",\n" +
                "\t\"Frameworkservice.exe\": \"Mcafee\",\n" +
                "\t\"egui.exe\": \"ESET NOD32\",\n" +
                "\t\"ekrn.exe\": \"ESET NOD32\",\n" +
                "\t\"eguiProxy.exe\": \"ESET NOD32\",\n" +
                "\t\"EShaSrv.exe\": \"ESET NOD32\",\n" +
                "\t\"kxetray.exe\": \"金山毒霸\",\n" +
                "\t\"kxescore.exe\": \"金山毒霸\",\n" +
                "\t\"kupdata.exe\": \"金山毒霸\",\n" +
                "\t\"kwsprotect64.exe\": \"金山毒霸\",\n" +
                "\t\"knsdtray.exe\": \"可牛杀毒\",\n" +
                "\t\"TMBMSRV.exe\": \"趋势杀毒\",\n" +
                "\t\"avcenter.exe\": \"Avira(小红伞)\",\n" +
                "\t\"avguard.exe\": \"Avira(小红伞)\",\n" +
                "\t\"avgnt.exe\": \"Avira(小红伞)\",\n" +
                "\t\"sched.exe\": \"Avira(小红伞)\",\n" +
                "\t\"ashDisp.exe\": \"Avast网络安全\",\n" +
                "\t\"rtvscan.exe\": \"诺顿杀毒\",\n" +
                "\t\"ccapp.exe\": \"Symantec Norton\",\n" +
                "\t\"NPFMntor.exe\": \"Norton杀毒软件相关进程\",\n" +
                "\t\"ccSetMgr.exe\": \"赛门铁克\",\n" +
                "\t\"ccRegVfy.exe\": \"Norton杀毒软件自身完整性检查程序\",\n" +
                "\t\"vptray.exe\": \"Norton病毒防火墙-盾牌图标程序\",\n" +
                "\t\"ksafe.exe\": \"金山卫士\",\n" +
                "\t\"QQPCRTP.exe\": \"QQ电脑管家\",\n" +
                "\t\"Miner.exe\": \"流量矿石\",\n" +
                "\t\"AYAgent.exe\": \"韩国胶囊\",\n" +
                "\t\"patray.exe\": \"安博士\",\n" +
                "\t\"V3Svc.exe\": \"安博士V3\",\n" +
                "\t\"avgwdsvc.exe\": \"AVG杀毒\",\n" +
                "\t\"QUHLPSVC.exe\": \"QUICK HEAL杀毒\",\n" +
                "\t\"mssecess.exe\": \"微软杀毒\",\n" +
                "\t\"SavProgress.exe\": \"Sophos杀毒\",\n" +
                "\t\"SophosUI.exe\": \"Sophos杀毒\",\n" +
                "\t\"SophosFS.exe\": \"Sophos杀毒\",\n" +
                "\t\"SophosHealth.exe\": \"Sophos杀毒\",\n" +
                "\t\"SophosSafestore64.exe\": \"Sophos杀毒\",\n" +
                "\t\"SophosCleanM.exe\": \"Sophos杀毒\",\n" +
                "\t\"fsavgui.exe\": \"F-Secure杀毒\",\n" +
                "\t\"vsserv.exe\": \"比特梵德\",\n" +
                "\t\"remupd.exe\": \"熊猫卫士\",\n" +
                "\t\"FortiTray.exe\": \"飞塔\",\n" +
                "\t\"safedog.exe\": \"安全狗\",\n" +
                "\t\"parmor.exe\": \"木马克星\",\n" +
                "\t\"Iparmor.exe.exe\": \"木马克星\",\n" +
                "\t\"beikesan.exe\": \"贝壳云安全\",\n" +
                "\t\"KSWebShield.exe\": \"金山网盾\",\n" +
                "\t\"TrojanHunter.exe\": \"木马猎手\",\n" +
                "\t\"GG.exe\": \"巨盾网游安全盾\",\n" +
                "\t\"adam.exe\": \"绿鹰安全精灵\",\n" +
                "\t\"AST.exe\": \"超级巡警\",\n" +
                "\t\"ananwidget.exe\": \"墨者安全专家\",\n" +
                "\t\"AVK.exe\": \"GData\",\n" +
                "\t\"avg.exe\": \"AVG Anti-Virus\",\n" +
                "\t\"spidernt.exe\": \"Dr.web\",\n" +
                "\t\"avgaurd.exe\": \"Avira Antivir\",\n" +
                "\t\"vsmon.exe\": \"ZoneAlarm\",\n" +
                "\t\"cpf.exe\": \"Comodo\",\n" +
                "\t\"outpost.exe\": \"Outpost Firewall\",\n" +
                "\t\"rfwmain.exe\": \"瑞星防火墙\",\n" +
                "\t\"kpfwtray.exe\": \"金山网镖\",\n" +
                "\t\"FYFireWall.exe\": \"风云防火墙\",\n" +
                "\t\"MPMon.exe\": \"微点主动防御\",\n" +
                "\t\"pfw.exe\": \"天网防火墙\",\n" +
                "\t\"S.exe\": \"在抓鸡\",\n" +
                "\t\"1433.exe\": \"在扫1433\",\n" +
                "\t\"DUB.exe\": \"在爆破\",\n" +
                "\t\"ServUDaemon.exe\": \"发现S-U\",\n" +
                "\t\"BaiduSdSvc.exe\": \"百度杀毒-服务进程\",\n" +
                "\t\"BaiduSdTray.exe\": \"百度杀毒-托盘进程\",\n" +
                "\t\"BaiduSd.exe\": \"百度杀毒-主程序\",\n" +
                "\t\"SafeDogGuardCenter.exe\": \"安全狗\",\n" +
                "\t\"safedogupdatecenter.exe\": \"安全狗\",\n" +
                "\t\"safedogguardcenter.exe\": \"安全狗\",\n" +
                "\t\"SafeDogSiteIIS.exe\": \"安全狗\",\n" +
                "\t\"SafeDogTray.exe\": \"安全狗\",\n" +
                "\t\"SafeDogServerUI.exe\": \"安全狗\",\n" +
                "\t\"D_Safe_Manage.exe\": \"D盾\",\n" +
                "\t\"d_manage.exe\": \"D盾\",\n" +
                "\t\"yunsuo_agent_service.exe\": \"云锁\",\n" +
                "\t\"yunsuo_agent_daemon.exe\": \"云锁\",\n" +
                "\t\"HwsPanel.exe\": \"护卫神\",\n" +
                "\t\"hws_ui.exe\": \"护卫神\",\n" +
                "\t\"hws.exe\": \"护卫神\",\n" +
                "\t\"hwsd.exe\": \"护卫神\",\n" +
                "\t\"hipstray.exe\": \"火绒\",\n" +
                "\t\"wsctrl.exe\": \"火绒\",\n" +
                "\t\"usysdiag.exe\": \"火绒\",\n" +
                "\t\"HipsDaemon.exe\": \"火绒\",\n" +
                "\t\"HipsLog.exe\": \"火绒\",\n" +
                "\t\"HipsMain.exe\": \"火绒\",\n" +
                "\t\"WEBSCANX.exe\": \"网络病毒克星\",\n" +
                "\t\"SPHINX.exe\": \"SPHINX防火墙\",\n" +
                "\t\"bddownloader.exe\": \"百度卫士\",\n" +
                "\t\"baiduansvx.exe\": \"百度卫士-主进程\",\n" +
                "\t\"AvastUI.exe\": \"Avast!5主程序\",\n" +
                "\t\"emet_agent.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"emet_service.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"firesvc.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"firetray.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"hipsvc.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"mfevtps.exe\": \"Mcafee\",\n" +
                "\t\"mcafeefire.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"scan32.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"shstat.exe\": \"Mcafee\",\n" +
                "\t\"vstskmgr.exe\": \"Mcafee\",\n" +
                "\t\"engineserver.exe\": \"Mcafee\",\n" +
                "\t\"mfeann.exe\": \"Mcafee\",\n" +
                "\t\"mcscript.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"updaterui.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"udaterui.exe\": \"Mcafee\",\n" +
                "\t\"naprdmgr.exe\": \"Mcafee\",\n" +
                "\t\"cleanup.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"cmdagent.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"frminst.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"mcscript_inuse.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"mctray.exe\": \"Mcafee\",\n" +
                "\t\"AAWTray.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"Ad-Aware.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"MSASCui.exe\": \"Windows Defender Antivirus\",\n" +
                "\t\"SecurityHealthService\": \"Windows Defender Antivirus\",\n" +
                "\t\"_avp32.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"_avpcc.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"_avpm.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"aAvgApi.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"ackwin32.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"adaware.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"advxdwin.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"agentsvr.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"agentw.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"alertsvc.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"alevir.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"alogserv.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"amon9x.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"anti-trojan.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"antivirus.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"ants.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"apimonitor.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"aplica32.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"apvxdwin.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"arr.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"atcon.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"atguard.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"atro55en.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"atupdater.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"atwatch.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"au.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"aupdate.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"auto-protect.nav80try.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"autodown.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"autotrace.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"autoupdate.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"avconsol.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"ave32.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"avgcc32.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"avgctrl.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"avgemc.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"avgrsx.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"avgserv.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"avgserv9.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"avgw.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"avkpop.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"avkserv.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"avkservice.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"avkwctl9.exe\": \"G Data文件系统实时监控\",\n" +
                "\t\"avltmain.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"avnt.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"avp32.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"avpcc.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"avpdos32.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"avpm.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"avptc32.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"avpupd.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"avsched32.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"avsynmgr.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"avwin.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"avwin95.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"avwinnt.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"avwupd.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"avwupd32.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"avwupsrv.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"avxmonitor9x.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"avxmonitornt.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"avxquar.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"backweb.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"bargains.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"bd_professional.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"beagle.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"belt.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"bidef.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"bidserver.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"bipcp.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"bipcpevalsetup.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"bisp.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"blackd.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"blackice.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"blink.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"blss.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"bootconf.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"bootwarn.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"borg2.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"bpc.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"brasil.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"bs120.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"bundle.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"bvt.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"ccevtmgr.exe\": \"赛门铁克\",\n" +
                "\t\"ccpxysvc.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"cdp.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"cfd.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"cfgwiz.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"cfiadmin.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"cfiaudit.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"cfinet.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"cfinet32.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"claw95.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"claw95cf.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"clean.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"cleaner.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"cleaner3.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"cleanpc.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"click.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"cmesys.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"cmgrdian.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"cmon016.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"connectionmonitor.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"cpd.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"cpf9x206.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"cpfnt206.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"ctrl.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"cv.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"cwnb181.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"cwntdwmo.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"datemanager.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"dcomx.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"defalert.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"defscangui.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"defwatch.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"deputy.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"divx.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"dllcache.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"dllreg.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"doors.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"dpf.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"dpfsetup.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"dpps2.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"drwatson.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"drweb32.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"drwebupw.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"dssagent.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"dvp95.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"dvp95_0.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"ecengine.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"efpeadm.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"emsw.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"ent.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"esafe.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"escanhnt.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"escanv95.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"espwatch.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"ethereal.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"etrustcipe.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"evpn.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"exantivirus-cnet.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"exe.avxw.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"expert.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"explore.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"f-agnt95.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"f-prot95.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"f-stopw.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"fameh32.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"fast.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"fch32.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"fih32.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"findviru.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"firewall.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"fnrb32.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"fp-win.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"fp-win_trial.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"fprot.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"frw.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"fsaa.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"fsav.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"fsav32.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"fsav530stbyb.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"fsav530wtbyb.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"fsav95.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"fsgk32.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"fsm32.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"fsma32.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"fsmb32.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"gator.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"gbmenu.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"gbpoll.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"generics.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"gmt.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"guard.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"guarddog.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"hacktracersetup.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"hbinst.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"hbsrv.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"hotactio.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"hotpatch.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"htlog.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"htpatch.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"hwpe.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"hxdl.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"hxiul.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"iamapp.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"iamserv.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"iamstats.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"ibmasn.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"ibmavsp.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"icload95.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"icloadnt.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"icmon.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"icsupp95.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"icsuppnt.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"idle.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"iedll.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"iedriver.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"iface.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"ifw2000.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"inetlnfo.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"infus.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"infwin.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"init.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"intdel.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"intren.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"iomon98.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"istsvc.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"jammer.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"jdbgmrg.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"jedi.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"kavlite40eng.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"kavpers40eng.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"kavpf.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"kazza.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"keenvalue.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"kerio-pf-213-en-win.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"kerio-wrl-421-en-win.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"kerio-wrp-421-en-win.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"kernel32.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"killprocesssetup161.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"launcher.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"ldnetmon.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"ldpro.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"ldpromenu.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"ldscan.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"lnetinfo.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"loader.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"localnet.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"lockdown.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"lockdown2000.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"lookout.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"lordpe.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"lsetup.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"luall.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"luau.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"lucomserver.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"luinit.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"luspt.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"mapisvc32.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"mcagent.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"mcmnhdlr.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"mctool.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"mcupdate.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"mcvsrte.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"mcvsshld.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"md.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"mfin32.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"mfw2en.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"mfweng3.02d30.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"mgavrtcl.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"mgavrte.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"mghtml.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"mgui.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"minilog.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"mmod.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"monitor.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"moolive.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"mostat.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"mpfagent.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"mpfservice.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"mpftray.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"mrflux.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"msapp.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"msbb.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"msblast.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"mscache.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"msccn32.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"mscman.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"msconfig.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"msdm.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"msdos.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"msiexec16.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"msinfo32.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"mslaugh.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"msmgt.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"msmsgri32.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"mssmmc32.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"mssys.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"msvxd.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"mu0311ad.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"mwatch.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"n32scanw.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"nav.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"navap.navapsvc.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"navapsvc.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"navapw32.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"navdx.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"navlu32.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"navnt.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"navstub.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"navw32.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"navwnt.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"nc2000.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"ncinst4.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"ndd32.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"neomonitor.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"neowatchlog.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"netarmor.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"netd32.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"netinfo.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"netmon.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"netscanpro.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"netspyhunter-1.2.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"netstat.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"netutils.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"nisserv.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"nisum.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"nmain.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"nod32.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"normist.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"norton_internet_secu_3.0_407.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"notstart.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"npf40_tw_98_nt_me_2k.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"npfmessenger.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"nprotect.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"npscheck.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"npssvc.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"nsched32.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"nssys32.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"nstask32.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"nsupdate.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"nt.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"ntrtscan.exe\": \"趋势科技防毒墙网络版客户端\",\n" +
                "\t\"ntvdm.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"ntxconfig.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"nui.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"nupgrade.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"nvarch16.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"nvc95.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"nvsvc32.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"nwinst4.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"nwservice.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"nwtool16.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"ollydbg.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"onsrvr.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"optimize.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"ostronet.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"otfix.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"outpostinstall.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"outpostproinstall.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"padmin.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"panixk.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"patch.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"pavcl.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"pavproxy.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"pavsched.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"pavw.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"pccwin98.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"pcfwallicon.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"pcip10117_0.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"pcscan.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"pdsetup.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"periscope.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"persfw.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"perswf.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"pf2.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"pfwadmin.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"pgmonitr.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"pingscan.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"platin.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"pop3trap.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"poproxy.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"popscan.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"portdetective.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"portmonitor.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"powerscan.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"ppinupdt.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"pptbc.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"ppvstop.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"prizesurfer.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"prmt.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"prmvr.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"procdump.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"processmonitor.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"procexplorerv1.0.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"programauditor.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"proport.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"protectx.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"pspf.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"purge.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"qconsole.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"qserver.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"rapapp.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"rav7.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"rav7win.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"rav8win32eng.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"ray.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"rb32.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"rcsync.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"realmon.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"reged.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"regedit.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"regedt32.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"rescue.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"rescue32.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"rrguard.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"rshell.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"rtvscn95.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"rulaunch.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"run32dll.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"rundll.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"rundll16.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"ruxdll32.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"safeweb.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"sahagent.exescan32.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"save.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"savenow.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"sbserv.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"sc.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"scam32.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"scan95.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"scanpm.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"scrscan.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"serv95.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"setup_flowprotector_us.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"setupvameeval.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"sfc.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"sgssfw32.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"sh.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"shellspyinstall.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"shn.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"showbehind.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"smc.exe\": \"赛门铁克\",\n" +
                "\t\"smcGui.exe\": \"赛门铁克\",\n" +
                "\t\"snac.exe\": \"赛门铁克\",\n" +
                "\t\"sms.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"smss32.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"soap.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"sofi.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"sperm.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"spf.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"spoler.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"spoolcv.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"spoolsv32.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"spyxx.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"srexe.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"srng.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"ss3edit.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"ssg_4104.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"ssgrate.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"st2.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"start.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"stcloader.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"supftrl.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"support.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"supporter5.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"svchostc.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"svchosts.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"sweep95.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"sweepnet.sweepsrv.sys.swnetsup.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"symproxysvc.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"symtray.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"sysedit.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"sysupd.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"taskmg.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"taskmo.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"taumon.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"tbscan.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"tc.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"tca.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"tcm.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"tds-3.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"tds2-98.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"tds2-nt.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"teekids.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"tfak.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"tfak5.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"tgbob.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"titanin.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"titaninxp.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"tracert.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"trickler.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"trjscan.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"trjsetup.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"trojantrap3.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"tsadbot.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"tvmd.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"tvtmd.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"undoboot.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"updat.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"update.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"upgrad.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"utpost.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"vbcmserv.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"vbcons.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"vbust.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"vbwin9x.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"vbwinntw.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"vcsetup.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"vet32.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"vet95.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"vettray.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"vfsetup.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"vir-help.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"virusmdpersonalfirewall.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"vnlan300.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"vnpc3000.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"vpc32.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"vpc42.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"vpfw30s.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"vscan40.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"vscenu6.02d30.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"vsched.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"vsecomr.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"vshwin32.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"vsisetup.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"vsmain.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"vsstat.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"vswin9xe.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"vswinntse.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"vswinperse.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"w32dsm89.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"w9x.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"watchdog.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"webdav.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"webtrap.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"wfindv32.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"whoswatchingme.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"wimmun32.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"win-bugsfix.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"win32.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"win32us.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"winactive.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"window.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"windows.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"wininetd.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"wininitx.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"winlogin.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"winmain.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"winnet.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"winppr32.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"winrecon.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"winservn.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"winssk32.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"winstart.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"winstart001.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"wintsk32.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"winupdate.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"wkufind.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"wnad.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"wnt.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"wradmin.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"wrctrl.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"wsbgate.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"wupdater.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"wupdt.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"wyvernworksfirewall.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"xpf202en.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"zapro.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"zapsetup3001.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"zatutor.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"zonalm2601.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"zonealarm.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"AVPM.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"A2CMD.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"A2SERVICE.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"A2FREE.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"ADVCHK.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"AGB.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"AKRNL.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"AHPROCMONSERVER.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"AIRDEFENSE.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"ALERTSVC.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"AVIRA.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"AMON.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"TROJAN.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"AVZ.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"ANTIVIR.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"APVXDWIN.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"ARMOR2NET.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"ASH.exeexe.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"ASHENHCD.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"ASHMAISV.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"ASHPOPWZ.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"ASHSERV.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"ASHSIMPL.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"ASHSKPCK.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"ASHWEBSV.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"ASWUPDSV.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"ASWSCAN.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"AVCIMAN.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"AVCONSOL.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"AVENGINE.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"AVESVC.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"AVEVAL.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"AVEVL32.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"AVGAM.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"AVGCC.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"AVGCHSVX.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"AVGCSRVX.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"AVGNSX.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"AVGCC32.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"AVGCTRL.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"AVGEMC.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"AVGFWSRV.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"AVGNTMGR.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"AVGSERV.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"AVGTRAY.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"AVGUPSVC.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"AVINITNT.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"AVKSERV.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"AVKSERVICE.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"AVKWCTL.exe\": \"G Data文件系统实时监控\",\n" +
                "\t\"AVP32.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"AVPCC.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"AVSERVER.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"AVSCHED32.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"AVSYNMGR.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"AVWUPD32.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"AVWUPSRV.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"AVXMONITOR.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"AVXQUAR.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"BDSWITCH.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"BLACKD.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"BLACKICE.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"CAFIX.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"BITDEFENDER.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"CCEVTMGR.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"CFP.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"CFPCONFIG.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"CFIAUDIT.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"CLAMTRAY.exe\": \"ClemWin Free Antivirus\",\n" +
                "\t\"clamscan.exe\": \"ClemWin Free Antivirus\",\n" +
                "\t\"CLAMWIN.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"CUREIT.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"DEFWATCH.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"DRVIRUS.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"DRWADINS.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"DRWEB.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"DEFENDERDAEMON.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"DWEBLLIO.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"DWEBIO.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"ESCANH95.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"ESCANHNT.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"EWIDOCTRL.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"EZANTIVIRUSREGISTRATIONCHECK.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"F-AGNT95.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"FAMEH32.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"FILEMON.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"FIREWALL.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"FORTICLIENT.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"FORTISCAN.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"FPAVSERVER.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"FPROTTRAY.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"FPWIN.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"FRESHCLAM.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"FSAV32.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"FSBWSYS.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"F-SCHED.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"FSDFWD.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"FSGK32.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"FSGK32ST.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"FSGUIEXE.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"FSMA32.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"FSMB32.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"FSPEX.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"FSSM32.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"F-STOPW.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"GCASDTSERV.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"GCASSERV.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"GIANTANTISPYWARE.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"GUARDGUI.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"GUARDNT.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"GUARDXSERVICE.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"GUARDXKICKOFF.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"HREGMON.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"HRRES.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"HSOCKPE.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"HUPDATE.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"IAMAPP.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"IAMSERV.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"ICLOAD95.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"ICLOADNT.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"ICMON.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"ICSSUPPNT.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"ICSUPP95.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"ICSUPPNT.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"INETUPD.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"INOCIT.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"INORPC.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"INORT.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"INOTASK.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"INOUPTNG.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"IOMON98.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"ISAFE.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"ISATRAY.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"KAV.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"KAVMM.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"KAVPF.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"KAVPFW.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"KAVSTART.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"KAVSVC.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"KAVSVCUI.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"KMAILMON.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"MAMUTU.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"MCAGENT.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"MCMNHDLR.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"MCREGWIZ.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"MCUPDATE.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"MCVSSHLD.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"MINILOG.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"MYAGTSVC.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"MYAGTTRY.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"NAVAPSVC.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"NAVAPW32.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"NAVLU32.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"NAVW32.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"NEOWATCHLOG.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"NEOWATCHTRAY.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"NISSERV.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"NISUM.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"NMAIN.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"NOD32.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"NORMIST.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"NOTSTART.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"NPAVTRAY.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"NPFMSG.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"NPROTECT.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"NSCHED32.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"NSMDTR.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"NSSSERV.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"NSSTRAY.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"NTRTSCAN.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"NTOS.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"NTXCONFIG.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"NUPGRADE.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"NVCOD.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"NVCTE.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"NVCUT.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"NWSERVICE.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"OFCPFWSVC.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"ONLINENT.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"OPSSVC.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"OP_MON.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"PAVFIRES.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"PAVFNSVR.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"PAVKRE.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"PAVPROT.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"PAVPROXY.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"PAVPRSRV.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"PAVSRV51.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"PAVSS.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"PCCGUIDE.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"PCCIOMON.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"PCCNTMON.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"PCCPFW.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"PCCTLCOM.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"PCTAV.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"PERSFW.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"PERTSK.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"PERVAC.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"PESTPATROL.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"PNMSRV.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"PREVSRV.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"PREVX.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"PSIMSVC.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"QHONLINE.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"QHONSVC.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"QHWSCSVC.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"QHSET.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"RTVSCN95.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"SALITY.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"SAPISSVC.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"SCANWSCS.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"SAVADMINSERVICE.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"SAVMAIN.exe\": \"Sophos Anti-Virus\",\n" +
                "\t\"SAVSCAN.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"SCANNINGPROCESS.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"SDRA64.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"SDHELP.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"SHSTAT.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"SITECLI.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"SPBBCSVC.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"SPIDERCPL.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"SPIDERML.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"SPIDERUI.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"SPYBOTSD.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"SPYXX.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"SS3EDIT.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"STOPSIGNAV.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"SWAGENT.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"SWDOCTOR.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"SWNETSUP.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"SYMLCSVC.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"SYMPROXYSVC.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"SYMSPORT.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"SYMWSC.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"SYNMGR.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"TAUMON.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"TMLISTEN.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"TMNTSRV.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"TMPROXY.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"TNBUTIL.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"TRJSCAN.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"VBA32ECM.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"VBA32IFS.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"VBA32LDR.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"VBA32PP3.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"VBSNTW.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"VCRMON.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"VRFWSVC.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"VRMONNT.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"VRMONSVC.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"VRRW32.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"VSECOMR.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"VSHWIN32.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"VSSTAT.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"WATCHDOG.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"WINSSNOTIFY.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"WRCTRL.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"XCOMMSVR.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"ZLCLIENT.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"ZONEALARM.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"360rp.exe\": \"360杀毒\",\n" +
                "\t\"afwServ.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"safeboxTray.exe\": \"360保险箱\",\n" +
                "\t\"360safebox.exe\": \"360保险箱\",\n" +
                "\t\"QQPCTray.exe\": \"腾讯电脑管家\",\n" +
                "\t\"QQPCNetFlow.exe\": \"腾讯电脑管家\",\n" +
                "\t\"QQPCRealTimeSpeedup.exe\": \"腾讯电脑管家\",\n" +
                "\t\"KSafeTray.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"KSafeSvc.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"KWatch.exe\": \"已知杀软进程,名称暂未收录\",\n" +
                "\t\"LiveUpdate360.exe\": \"360杀毒\",\n" +
                "\t\"MBAMService.exe\": \"Malwarebytes Anti-Malware\",\n" +
                "\t\"mbam.exe\": \"Malwarebytes Anti-Malware\",\n" +
                "\t\"mbamtray.exe\": \"Malwarebytes Anti-Malware\",\n" +
                "\t\"GDScan.exe\": \"G Data扫描器\",\n" +
                "\t\"AVKProxy.exe\": \"G Data杀毒代理\",\n" +
                "\t\"AVKBackupService.exe\": \"G Data备份服务\",\n" +
                "\t\"AVK.exe\": \"G Data安全软件客户端\",\n" +
                "\t\"Notifier.exe\": \"亚信安全服务器深度安全防护系统\",\n" +
                "\t\"D_Safe_Manage.exe\": \"D盾\",\n" +
                "\t\"d_manage.exe\": \"D盾\",\n" +
                "\t\"yunsuo_agent_service.exe\": \"云锁\",\n" +
                "\t\"yunsuo_agent_daemon.exe\": \"云锁\",\n" +
                "\t\"AliYunDun.exe\": \"阿里云盾\",\n" +
                "\t\"AliYunDunUpdate.exe\": \"阿里云盾\",\t\n" +
                "\t\"aliyun_assist_service.exe\": \"阿里云盾\",\n" +
                "\t\"BaradAgent.exe\": \"腾讯云安全\",\n" +
                "\t\"sgagent.exe\": \"腾讯云安全\",\n" +
                "\t\"YDService.exe\": \"腾讯云安全\",\n" +
                "\t\"YDLive.exe\": \"腾讯云安全\",\n" +
                "\t\"YDEdr.exe\": \"腾讯云安全\",\n" +
                "\t\"360WebSafe.exe\": \"360主机卫士Web\",\n" +
                "\t\"QHSrv.exe\": \"360主机卫士Web\",\n" +
                "\t\"QHWebshellGuard.exe\": \"360主机卫士Web\",\n" +
                "\t\"SafeDogSiteApache.exe\": \"安全狗\",\n" +
                "\t\"SafeDogSiteIIS.exe\": \"安全狗\",\n" +
                "\t\"SafeDogTray.exe\": \"安全狗\",\n" +
                "\t\"SafeDogServerUI.exe\": \"安全狗\",\n" +
                "\t\"SafeDogGuardCenter.exe\": \"安全狗\",\n" +
                "\t\"CloudHelper.exe\": \"安全狗\",\n" +
                "\t\"SafeDogUpdateCenter.exe\": \"安全狗\",\n" +
                "\t\"hws.exe\": \"护卫神·入侵防护系统\",\n" +
                "\t\"hwsd.exe\": \"护卫神·入侵防护系统\",\n" +
                "\t\"hws_ui.exe\": \"护卫神·入侵防护系统\",\n" +
                "\t\"HwsPanel.exe\": \"护卫神·入侵防护系统\",\n" +
                "\t\"HwsHostPanel.exe\": \"护卫神·入侵防护系统\",\n" +
                "\t\"HwsHostMaster.exe\": \"护卫神·入侵防护系统\",\n" +
                "\t\"gov_defence_service.exe\": \"网防G01\",\n" +
                "\t\"gov_defence_daemon.exe\": \"网防G01\"\n" +
                "}\n";


        return json;
    }


    public static HashMap<String, String> TestContext(String searchKey) {

//        System.out.println(antivirusConntroller());
        JSONObject json = JSONObject.parseObject(antivirusConntroller());

        HashMap<String, String> Sites = new HashMap<>();

        for (String key : json.keySet()) {
            if (key.contains(searchKey) || json.getString(key).contains(searchKey)) {
                Sites.put(key, json.getString(key));
            }
        }
        System.out.println(Sites);

        return Sites;
    }


    public static void main(String[] args) {

        TestContext("360tray");
        TestContext("cleaner8");
        TestContext("ccRegVfy");

       String str =  "svchost.exe   " ;
       TestContext(str);
    }
}
